In [14]:
import numpy as np
from pprint import pprint

In [17]:
d = [[0, 0.24, 0.22, 0.37, 0.34, 0.23], 
     [0.24, 0, 0.15, 0.2, 0.14, 0.25],
     [0.22, 0.15, 0, 0.15, 0.28, 0.11],
     [0.37, 0.2, 0.15, 0, 0.29, 0.22],
     [0.34, 0.14, 0.28, 0.29, 0, 0.39],
     [0.23, 0.25, 0.11, 0.22, 0.39, 0]]

In [5]:
def update(dist, i, j, k, alpha1, alpha2, beta, gamma):
    return alpha1 * dist[i][k] + alpha2 * dist[j][k] + beta * dist[i][j] + \
        gamma * abs(dist[i][k] - dist[j][k])

In [6]:
def single_link(dist, i, j, k):
    return update(dist, i, j, k, 0.5, 0.5, 0, -0.5)

In [29]:
d1 = np.copy(d)

In [36]:
d1[d1 == 0] = np.max(d1) + 1

In [37]:
d1

array([[1.39, 0.24, 0.22, 0.37, 0.34, 0.23],
       [0.24, 1.39, 0.15, 0.2 , 0.14, 0.25],
       [0.22, 0.15, 1.39, 0.15, 0.28, 0.11],
       [0.37, 0.2 , 0.15, 1.39, 0.29, 0.22],
       [0.34, 0.14, 0.28, 0.29, 1.39, 0.39],
       [0.23, 0.25, 0.11, 0.22, 0.39, 1.39]])

In [40]:
indices = np.unravel_index(np.argmin(d1), d1.shape)

In [41]:
d2 = np.delete(d1, indices[0], axis=0)
d2 = np.delete(d2, indices[1] - 1, axis=0)

d2 = np.delete(d2, indices[0], axis=1)
d2 = np.delete(d2, indices[1] - 1, axis=1)

In [42]:
d2

array([[1.39, 0.24, 0.37, 0.34],
       [0.24, 1.39, 0.2 , 0.14],
       [0.37, 0.2 , 1.39, 0.29],
       [0.34, 0.14, 0.29, 1.39]])

In [45]:
d2 = np.insert(d2, 0, 0, axis=1)
d2 = np.insert(d2, 0, 0, axis=0)
d2

array([[0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 1.39, 0.24, 0.37, 0.34],
       [0.  , 0.24, 1.39, 0.2 , 0.14],
       [0.  , 0.37, 0.2 , 1.39, 0.29],
       [0.  , 0.34, 0.14, 0.29, 1.39]])

At this point, the index--point mappings are as below:  

* 0: Cluster (3, 6)
* 1: (1)
* 2: (2)
* 3: (4)
* 4: (5)

In [51]:
cur_index = 0
for i in range(len(d)):
    if i not in indices:
        cur_index += 1
        d2[0][cur_index] = d2[cur_index][0] = single_link(d1, indices[0], indices[1], i)
        print(cur_index, single_link(d1, indices[0], indices[1], i))

1 0.22
2 0.15000000000000002
3 0.15
4 0.28


In [56]:
d2[0][0] = d2[1][1]  # Make this also a high value
d2

array([[1.39, 0.22, 0.15, 0.15, 0.28],
       [0.22, 1.39, 0.24, 0.37, 0.34],
       [0.15, 0.24, 1.39, 0.2 , 0.14],
       [0.15, 0.37, 0.2 , 1.39, 0.29],
       [0.28, 0.34, 0.14, 0.29, 1.39]])

Note that the diagonal elements here are actually 0. We now repeat this process.

In [57]:
indices = np.unravel_index(np.argmin(d2), d2.shape)

In [58]:
indices

(2, 4)

This means we're merging points 2 and 5 now (see the mapping we wrote above).

In [59]:
d3 = np.delete(d2, indices[0], axis=0)
d3 = np.delete(d3, indices[1] - 1, axis=0)

d3 = np.delete(d3, indices[0], axis=1)
d3 = np.delete(d3, indices[1] - 1, axis=1)

In [60]:
d3

array([[1.39, 0.22, 0.15],
       [0.22, 1.39, 0.37],
       [0.15, 0.37, 1.39]])

In [61]:
d3 = np.insert(d3, 0, 0, axis=1)
d3 = np.insert(d3, 0, 0, axis=0)
d3

array([[0.  , 0.  , 0.  , 0.  ],
       [0.  , 1.39, 0.22, 0.15],
       [0.  , 0.22, 1.39, 0.37],
       [0.  , 0.15, 0.37, 1.39]])

Our mapping is now as follows:

|Index|Original points  
|---|---|
|0|(2, 5)|
|1|(3, 6)|
|2|(1)|
|3|(4)|

In [63]:
cur_index = 0
for i in range(len(d2)):
    if i not in indices:
        cur_index += 1
        d3[0][cur_index] = d3[cur_index][0] = single_link(d2, indices[0], indices[1], i)
        print(cur_index, single_link(d2, indices[0], indices[1], i))

1 0.15000000000000002
2 0.24000000000000002
3 0.2


In [64]:
d3

array([[0.  , 0.15, 0.24, 0.2 ],
       [0.15, 1.39, 0.22, 0.15],
       [0.24, 0.22, 1.39, 0.37],
       [0.2 , 0.15, 0.37, 1.39]])

In [65]:
d3[0][0] = d3[1][1]
d3

array([[1.39, 0.15, 0.24, 0.2 ],
       [0.15, 1.39, 0.22, 0.15],
       [0.24, 0.22, 1.39, 0.37],
       [0.2 , 0.15, 0.37, 1.39]])

Repeat again

In [68]:
indices = np.unravel_index(np.argmin(d3), d3.shape)
print(indices)

d4 = np.delete(d3, indices[0], axis=0)
d4 = np.delete(d4, indices[1] - 1, axis=0)

d4 = np.delete(d4, indices[0], axis=1)
d4 = np.delete(d4, indices[1] - 1, axis=1)

d4 = np.insert(d4, 0, 0, axis=1)
d4 = np.insert(d4, 0, 0, axis=0)

cur_index = 0
for i in range(len(d3)):
    if i not in indices:
        cur_index += 1
        d4[0][cur_index] = d4[cur_index][0] = single_link(d3, indices[0], indices[1], i)
        print(cur_index, single_link(d3, indices[0], indices[1], i))

(1, 3)
1 0.15000000000000002
2 0.21999999999999997


In [69]:
d4[0][0] = d4[1][1]
d4

array([[1.39, 0.15, 0.22],
       [0.15, 1.39, 0.24],
       [0.22, 0.24, 1.39]])

## Function to automatically cluster

Let's now write a function to generalize this process.

In [74]:
from sklearn.metrics import pairwise_distances

In [118]:
def hierarchical_cluster(points, metric='euclidean'):
    dist = pairwise_distances(points, metric=metric)
    print('Distance matrix:')
    print(dist)
    
    dist[dist == 0] = np.max(dist) + 1
    
    # Maintain a list of clusters
    clusters = [str(i) for i in range(1, len(dist) + 1)]
    
    # Convert to numpy array and set dtype of appropriate size
    dtype = '<U' + str(5 * sum([len(i) for i in clusters]))
    clusters = np.array(clusters, dtype=dtype)
    
    for _ in range(len(dist) - 1):
        # Find the indices of the minimum element
        indices = np.unravel_index(np.argmin(dist), dist.shape)

        # Update the cluster list
        c1 = clusters[indices[0]]
        c2 = clusters[indices[1]]
        new_cluster = '(' + c1 + ', ' + c2 + ')'
        print(new_cluster)
        clusters = np.delete(clusters, indices)
        clusters = np.insert(clusters, 0, new_cluster, axis=0)
        print('Clusters:', clusters)

        # Build a new distance matrix: start by removing the older points
        new_dist = np.delete(dist, indices[0], axis=0)
        new_dist = np.delete(new_dist, indices[1] - 1, axis=0)
        new_dist = np.delete(new_dist, indices[0], axis=1)
        new_dist = np.delete(new_dist, indices[1] - 1, axis=1)

        # Next, add the combined cluster at the beginning. Start by
        # creating spaces for the distances between this new cluster
        # and all other clusters.
        new_dist = np.insert(new_dist, 0, 0, axis=1)
        new_dist = np.insert(new_dist, 0, 0, axis=0)

        # Fill in values of the distances using the Lance-Williams equation
        cur_index = 0
        for i in range(len(dist)):
            if i not in indices:
                cur_index += 1
                new_dist[0][cur_index] = new_dist[cur_index][0] = single_link(dist, 
                                                                              indices[0], 
                                                                              indices[1], 
                                                                              i)
        new_dist[0][0] = np.max(new_dist) + 1
        dist = new_dist
    
    return clusters

In [119]:
hierarchical_cluster([[0.4, 0.53], [0.22, 0.38], [0.35, 0.32], [0.26, 0.19], [0.08, 0.41], [0.45, 0.30]])

Distance matrix:
[[0.         0.23430749 0.21587033 0.36769553 0.34176015 0.23537205]
 [0.23430749 0.         0.14317821 0.19416488 0.14317821 0.24351591]
 [0.21587033 0.14317821 0.         0.15811388 0.28460499 0.10198039]
 [0.36769553 0.19416488 0.15811388 0.         0.28425341 0.21954498]
 [0.34176015 0.14317821 0.28460499 0.28425341 0.         0.38600518]
 [0.23537205 0.24351591 0.10198039 0.21954498 0.38600518 0.        ]]
(3, 6)
Clusters: ['(3, 6)' '1' '2' '4' '5']
(2, 5)
Clusters: ['(2, 5)' '(3, 6)' '1' '4']
((2, 5), (3, 6))
Clusters: ['((2, 5), (3, 6))' '1' '4']
(((2, 5), (3, 6)), 4)
Clusters: ['(((2, 5), (3, 6)), 4)' '1']
((((2, 5), (3, 6)), 4), 1)
Clusters: ['((((2, 5), (3, 6)), 4), 1)']


array(['((((2, 5), (3, 6)), 4), 1)'], dtype='<U30')